site_name: Python Geospatial Engineering Practices
site_description: Practical patterns and drills for high-quality Python development with geospatial data
theme:
  name: material
  palette:
  - scheme: default
    primary: blue grey
    accent: red
  - scheme: slate
    primary: blue grey
    accent: red
  features:
  - navigation.tabs
  - navigation.sections
  - toc.follow
  - search.suggest
  - content.code.copy
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths:
        - ..
        setup_commands:
        - import sys, os
        - sys.path.insert(0, os.path.abspath(".."))
        options:
          show_source: true
          show_root_heading: true
markdown_extensions:
- admonition
- tables
- toc
- attr_list
- pymdownx.details
- pymdownx.highlight
- pymdownx.superfences
- pymdownx.tabbed
- pymdownx.emoji
- pymdownx.magiclink
extra_css:
- stylesheets/extra.css
extra_javascript:
- javascripts/config.js
nav:
- Home: index.md
- Overview:
  - Study Plan: study_plan.md
- Training Modules:
  - Day 01 - Concurrency:
    - Concurrency: day01_concurrency/index.md
  - Day 02 - Oop:
    - OOP: day02_oop/index.md
  - Day 03 - Api:
    - APIs: day03_api/index.md
  - Day 04 - Testing:
    - Testing: day04_testing/index.md
  - Day 05 - Data:
    - Data: day05_data/index.md
  - Day 06 - Perf:
    - Performance: day06_perf/index.md
  - Day 07 - Mock:
    - Mock Project: day07_mock/index.md
